blank_issues_enabled: false
contact_links:
  - name: ⚠️ Extension/source issue
    url: https://github.com/tachiyomiorg/extensions/issues/new/choose
    about: Issues and requests for official extensions and sources should be opened in the extensions repository instead
  - name: 📦 Mihon extensions
    url: https://mihon.app/extensions/
    about: List of all available extensions with download links
  - name: 🖥️ Mihon website
    url: https://mihon.app/
    about: Guides, troubleshooting, and answers to common questions
